UNDERWEIGHT = 'Twoje BMI wskazuje na niedowagę'
NORMAL = 'Twoje BMI jest w normie'
OVERWEIGHT = 'Twoje BMI wskazuje na nadwagę'
OBESE = 'Twoje BMI wskazuje na otyłość'
EXTREMELY_OBESE = 'Twoje BMI wskazuje na otyłość II stopnia'
